In [1]:
# EXP no.:5

In [2]:
# Aim: to perform creation of arrays using numpy

In [3]:
# NAME: Kartiki Yawatkar
# Roll no:66
#SEC:A
# Subject:Emerging Technology 1(ET 1)
#Date:12/8/2025

# To perform Creation of Arrays using numpy

In [4]:
import numpy as np

In [5]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  


In [6]:
print(arr1)

[1 2 3 4]


In [7]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
arr3 = np.array([1, 2, 3], dtype=float)  
arr4 = np.array([1, 2, 3], dtype=np.int32)


In [9]:
arr3

array([1., 2., 3.])

# Creating 1D Array using numpy

In [10]:
a1 = np.array([10,20,30,40,50])

In [11]:
a1

array([10, 20, 30, 40, 50])

# Creating 2D Array using numpy

In [13]:
a2 = np.array([[10,20,30,40,50],
               [60,70,80,90,100]])


In [14]:
a2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])